# Site settings
title: Hey Hannah - Your Text to Image App
email: # Force redeploy trigger
description: >-
Have something to say? Write it in Hey Hannah and post it to your socials, send it via iMessage or save & share it as a photo -- all free and open source.
baseurl: "/hey-hannah"
url: "https://decentralizeddan.github.io/hey-hannah"

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - App.js
  - index.js
  - app.json
  - eas.json
  - assets/adaptive-icon.png
  - assets/favicon.png
  - assets/icon.png
  - assets/splash-icon.png
  - generate-icon.html
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md

# Collection settings
# collections:
#   features:
#     output: false

# Site configuration
timezone: America/Los_Angeles
permalink: /:categories/:year/:month/:day/:title/

# SEO settings
author:
twitter:
  username:
  card: summary

# App-specific settings
app:
  name: "Hey Hannah"
  version: "1.0.0"
  platform: "iOS"
  status: "In Development"
  license: "GPL-3.0"
  app_store_url: ""
  github_repo: "https://github.com/DecentralizedDan/hey-hannah"

# Color scheme
colors:
  - white
  - black
  - red
  - blue
  - green
  - yellow
  - purple
  - orange

# Social links
github_username: DecentralizedDan
