# Site settings
title: Hey Hannah - Your Text to Image App
email:
description: >-
Have something to say? Write it in Hey Hannah and post it to your socials, 
send it via iMessage or save & share it as a photo -- with 8 colors and 3 
fonts to choose from! This app is free and open source.

baseurl: ""
url: "https://heyhannah.app"

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - App.js
  - index.js
  - app.json
  - eas.json
  - assets/
  - generate-icon.html
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md

# Collection settings
collections:
  features:
    output: false

# Site configuration
timezone: America/New_York
permalink: /:categories/:year/:month/:day/:title/

# SEO settings
author:
twitter:
  username:
  card: summary

# App-specific settings
app:
  name: "Hey Hannah"
  version: "1.0.0"
  platform: "iOS"
  status: "In Development"
  license: "GPL-3.0"
  app_store_url: ""
  github_repo: "https://github.com/DecentralizedDan/hey-hannah"

# Color scheme
colors:
  - white
  - black
  - red
  - blue
  - green
  - yellow
  - purple
  - orange

# Features
features:
  - name: "Text Creation & Editing"
    description: "Type and edit text with ease"
  - name: "Image Export"
    description: "Save text as JPG images"
  - name: "Sharing"
    description: "Copy images to clipboard or share to other apps"
  - name: "Color Options"
    description: "Choose from 8 colors for background and text"

# Social links
github_username: DecentralizedDan
